export const fontConfig = {
  "Archivo-Bold": require("../../assets/fonts/Archivo-Bold.ttf"),
  "Archivo-BoldItalic": require("../../assets/fonts/Archivo-BoldItalic.ttf"),
  "Archivo-Italic": require("../../assets/fonts/Archivo-Italic.ttf"),
  "Archivo-Medium": require("../../assets/fonts/Archivo-Medium.ttf"),
  "Archivo-MediumItalic": require("../../assets/fonts/Archivo-MediumItalic.ttf"),
  "Archivo-Regular": require("../../assets/fonts/Archivo-Regular.ttf"),
  "Archivo-SemiBold": require("../../assets/fonts/Archivo-SemiBold.ttf"),
  "Archivo-SemiBoldItalic": require("../../assets/fonts/Archivo-SemiBoldItalic.ttf"),
  "Inter-Bold": require("../../assets/fonts/Inter-Bold.ttf"),
  "Inter-Medium": require("../../assets/fonts/Inter-Medium.ttf"),
  "Mulish-Regular": require("../../assets/fonts/Mulish-Regular.ttf"),
  "Mulish-Semibold": require("../../assets/fonts/Mulish-SemiBold.ttf"),
  "Mulish-Bold": require("../../assets/fonts/Mulish-Bold.ttf"),
};
